
image:
  repository: docker.github.io/IpsoVeritas/proxy
  tag: latest
  pullPolicy: IfNotPresent

port: 6519
base: https://lars.ngrok.io

log:
  level: debug
  formatter: text

service:
  annotations: {}

ingress:
  enabled: false
  hostname: "*.proxy.localhost"

  annotations: {}