apiVersion: v1
kind: Service
metadata:
  name: proxy
  labels:
    app: proxy
    release: {{ .Release.Name }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.port }}
    name: api
  selector:
    app: proxy